### ISSUE TITLE
Datatypes

### ISSUE THREAD

**Issue by sifat144** [johnfrench3/node-postgres-repos#120]
Mate, you need a 'datatype' section on your Wiki. Everyone who's involved in RDBMS space has one...and there's a good reason for it.

I can understand I might need to spend an hour googling to learn how to do some esoteric piece of SQL weirdness - but not...how to insert a TIMESTAMPZ.

**Comment by johnfrench3** [comment]
Good call! I'm overhauling the documentation majorly in the next few weeks. I'll be sure to add a note to add this as well!
